<?php

class IbpTableSeeder extends Seeder
{
    public function run()
    {
        // Uncomment the below to wipe the table clean before populating
        DB::table('ibp')->truncate();

        $ibp = array(
            array(
                  'id' => 1,
                  'product_id' => 1,
                  'province_id' => 5,
                  'median' => 12.00,
                  'min' => 8.00,
                  'max' =>  19.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 2,
                  'product_id' => 2,
                  'province_id' => 5,
                  'median' => 15.00,
                  'min' => 7.58,
                  'max' =>  30.30,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 3,
                  'product_id' => 3,
                  'province_id' => 5,
                  'median' => 23.88,
                  'min' => 12.00,
                  'max' =>  33.33,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 4,
                  'product_id' => 4,
                  'province_id' => 5,
                  'median' => 7.20,
                  'min' => 3.50,
                  'max' =>  12.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 5,
                  'product_id' => 5,
                  'province_id' => 5,
                  'median' => 9.00,
                  'min' => 5.00,
                  'max' =>  14.90,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 6,
                  'product_id' => 6,
                  'province_id' => 5,
                  'median' => 6.50,
                  'min' => 3.00,
                  'max' =>  12.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 7,
                  'product_id' => 7,
                  'province_id' => 5,
                  'median' => 7.00,
                  'min' => 4.00,
                  'max' =>  13.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 8,
                  'product_id' => 8,
                  'province_id' => 5,
                  'median' => 7.00,
                  'min' => 5.50,
                  'max' =>  9.50,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 9,
                  'product_id' => 9,
                  'province_id' => 5,
                  'median' => 5.75,
                  'min' => 4.00,
                  'max' =>  8.50,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 10,
                  'product_id' => 10,
                  'province_id' => 5,
                  'median' => 17.70,
                  'min' => 12.00,
                  'max' =>  32.90,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 11,
                  'product_id' => 11,
                  'province_id' => 5,
                  'median' => 10.00,
                  'min' => 6.50,
                  'max' =>  16.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 12,
                  'product_id' => 12,
                  'province_id' => 5,
                  'median' => 7.75,
                  'min' => 5.00,
                  'max' =>  12.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 13,
                  'product_id' => 13,
                  'province_id' => 5,
                  'median' => 55.00,
                  'min' => 30.00,
                  'max' =>  90.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 14,
                  'product_id' => 14,
                  'province_id' => 5,
                  'median' => 42.33,
                  'min' => 30.00,
                  'max' =>  60.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 15,
                  'product_id' => 15,
                  'province_id' => 5,
                  'median' => 42.50,
                  'min' => 25.60,
                  'max' =>  63.90,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 16,
                  'product_id' => 16,
                  'province_id' => 5,
                  'median' => 150.00,
                  'min' => 62.50,
                  'max' =>  200.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 17,
                  'product_id' => 17,
                  'province_id' => 5,
                  'median' => 10.00,
                  'min' => 5.00,
                  'max' =>  17.90,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 18,
                  'product_id' => 18,
                  'province_id' => 5,
                  'median' => 3.00,
                  'min' => 2.00,
                  'max' =>  11.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 19,
                  'product_id' => 19,
                  'province_id' => 5,
                  'median' => 3.50,
                  'min' => 2.00,
                  'max' =>  7.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 20,
                  'product_id' => 20,
                  'province_id' => 5,
                  'median' => 6.00,
                  'min' => 4.00,
                  'max' =>  12.60,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 21,
                  'product_id' => 21,
                  'province_id' => 5,
                  'median' => 27.60,
                  'min' => 17.00,
                  'max' =>  40.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 22,
                  'product_id' => 22,
                  'province_id' => 5,
                  'median' => 4.00,
                  'min' => 2.50,
                  'max' =>  7.50,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 23,
                  'product_id' => 23,
                  'province_id' => 5,
                  'median' => 12.00,
                  'min' => 7.90,
                  'max' =>  17.60,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 24,
                  'product_id' => 24,
                  'province_id' => 5,
                  'median' => 8.00,
                  'min' => 4.00,
                  'max' =>  13.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 25,
                  'product_id' => 25,
                  'province_id' => 5,
                  'median' => 10.00,
                  'min' => 4.00,
                  'max' =>  16.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 26,
                  'product_id' => 26,
                  'province_id' => 5,
                  'median' => 5.00,
                  'min' => 3.00,
                  'max' =>  10.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 27,
                  'product_id' => 27,
                  'province_id' => 5,
                  'median' => 5.00,
                  'min' => 3.00,
                  'max' =>  8.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 28,
                  'product_id' => 28,
                  'province_id' => 5,
                  'median' => 10.00,
                  'min' => 6.00,
                  'max' =>  17.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 29,
                  'product_id' => 29,
                  'province_id' => 5,
                  'median' => 7.00,
                  'min' => 4.05,
                  'max' =>  14.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 30,
                  'product_id' => 30,
                  'province_id' => 5,
                  'median' => 8.00,
                  'min' => 4.00,
                  'max' =>  13.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 31,
                  'product_id' => 31,
                  'province_id' => 5,
                  'median' => 6.00,
                  'min' => 4.00,
                  'max' =>  8.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 32,
                  'product_id' => 32,
                  'province_id' => 5,
                  'median' => 10.00,
                  'min' => 6.00,
                  'max' =>  19.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 33,
                  'product_id' => 33,
                  'province_id' => 5,
                  'median' => 13.00,
                  'min' => 5.00,
                  'max' =>  27.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 34,
                  'product_id' => 34,
                  'province_id' => 5,
                  'median' => 5.50,
                  'min' => 3.00,
                  'max' =>  8.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 35,
                  'product_id' => 35,
                  'province_id' => 5,
                  'median' => 9.00,
                  'min' => 4.00,
                  'max' =>  15.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 36,
                  'product_id' => 36,
                  'province_id' => 5,
                  'median' => 4.00,
                  'min' => 3.00,
                  'max' =>  6.50,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 37,
                  'product_id' => 37,
                  'province_id' => 5,
                  'median' => 5.00,
                  'min' => 3.65,
                  'max' =>  9.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 38,
                  'product_id' => 38,
                  'province_id' => 5,
                  'median' => 7.00,
                  'min' => 3.70,
                  'max' =>  15.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 39,
                  'product_id' => 39,
                  'province_id' => 5,
                  'median' => 10.00,
                  'min' => 5.00,
                  'max' =>  16.67,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 40,
                  'product_id' => 40,
                  'province_id' => 5,
                  'median' => 10.00,
                  'min' => 6.00,
                  'max' =>  15.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 41,
                  'product_id' => 41,
                  'province_id' => 5,
                  'median' => 5.56,
                  'min' => 3.33,
                  'max' =>  11.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 42,
                  'product_id' => 42,
                  'province_id' => 5,
                  'median' => 13.00,
                  'min' => 10.00,
                  'max' =>  19.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 43,
                  'product_id' => 43,
                  'province_id' => 5,
                  'median' => 38.00,
                  'min' => 18.00,
                  'max' =>  60.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 44,
                  'product_id' => 44,
                  'province_id' => 5,
                  'median' => 20.00,
                  'min' => 11.00,
                  'max' =>  30.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 45,
                  'product_id' => 45,
                  'province_id' => 5,
                  'median' => 29.00,
                  'min' => 15.00,
                  'max' =>  42.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 46,
                  'product_id' => 46,
                  'province_id' => 5,
                  'median' => 43.70,
                  'min' => 30.00,
                  'max' =>  62.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 47,
                  'product_id' => 47,
                  'province_id' => 5,
                  'median' => 35.00,
                  'min' => 22.00,
                  'max' =>  58.50,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 48,
                  'product_id' => 48,
                  'province_id' => 5,
                  'median' => 46.00,
                  'min' => 30.00,
                  'max' =>  74.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 49,
                  'product_id' => 49,
                  'province_id' => 5,
                  'median' => 40.00,
                  'min' => 24.00,
                  'max' =>  55.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 50,
                  'product_id' => 50,
                  'province_id' => 5,
                  'median' => 16.00,
                  'min' => 12.00,
                  'max' =>  35.00,
                  'reported_at' => new DateTime('2013-09-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 51,
                  'product_id' => 1,
                  'province_id' => 5,
                  'median' => 14.00,
                  'min' => 10.00,
                  'max' => 19.90,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 52,
                  'product_id' => 2,
                  'province_id' => 5,
                  'median' => 17.00,
                  'min' => 7.58,
                  'max' => 50.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 53,
                  'product_id' => 3,
                  'province_id' => 5,
                  'median' => 24.00,
                  'min' => 15.00,
                  'max' => 37.50,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 54,
                  'product_id' => 4,
                  'province_id' => 5,
                  'median' => 7.39,
                  'min' => 3.80,
                  'max' => 12.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 55,
                  'product_id' => 5,
                  'province_id' => 5,
                  'median' => 10.00,
                  'min' => 5.00,
                  'max' => 13.50,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 56,
                  'product_id' => 6,
                  'province_id' => 5,
                  'median' => 6.00,
                  'min' => 3.00,
                  'max' => 10.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 57,
                  'product_id' => 7,
                  'province_id' => 5,
                  'median' => 7.50,
                  'min' => 4.50,
                  'max' => 15.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 58,
                  'product_id' => 8,
                  'province_id' => 5,
                  'median' => 7.50,
                  'min' => 5.50,
                  'max' => 9.50,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 59,
                  'product_id' => 9,
                  'province_id' => 5,
                  'median' => 6.00,
                  'min' => 4.25,
                  'max' => 8.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 60,
                  'product_id' => 10,
                  'province_id' => 5,
                  'median' => 18.00,
                  'min' => 9.00,
                  'max' => 32.90,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 61,
                  'product_id' => 11,
                  'province_id' => 5,
                  'median' => 10.00,
                  'min' => 6.00,
                  'max' => 15.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 62,
                  'product_id' => 12,
                  'province_id' => 5,
                  'median' => 8.00,
                  'min' => 5.50,
                  'max' => 13.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 63,
                  'product_id' => 13,
                  'province_id' => 5,
                  'median' => 60.00,
                  'min' => 33.00,
                  'max' => 83.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 64,
                  'product_id' => 14,
                  'province_id' => 5,
                  'median' => 40.00,
                  'min' => 26.67,
                  'max' => 60.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 65,
                  'product_id' => 15,
                  'province_id' => 5,
                  'median' => 42.90,
                  'min' => 25.00,
                  'max' => 70.99,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 66,
                  'product_id' => 16,
                  'province_id' => 5,
                  'median' => 150.00,
                  'min' => 87.50,
                  'max' => 212.50,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 67,
                  'product_id' => 17,
                  'province_id' => 5,
                  'median' => 10.00,
                  'min' => 4.99,
                  'max' => 17.77,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 68,
                  'product_id' => 18,
                  'province_id' => 5,
                  'median' => 3.00,
                  'min' => 1.90,
                  'max' => 5.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 69,
                  'product_id' => 19,
                  'province_id' => 5,
                  'median' => 3.75,
                  'min' => 2.00,
                  'max' => 8.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 70,
                  'product_id' => 20,
                  'province_id' => 5,
                  'median' => 5.50,
                  'min' => 3.00,
                  'max' => 11.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 71,
                  'product_id' => 21,
                  'province_id' => 5,
                  'median' => 26.00,
                  'min' => 16.00,
                  'max' => 40.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 72,
                  'product_id' => 22,
                  'province_id' => 5,
                  'median' => 4.00,
                  'min' => 2.00,
                  'max' => 7.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 73,
                  'product_id' => 23,
                  'province_id' => 5,
                  'median' => 13.00,
                  'min' => 7.00,
                  'max' => 20.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 74,
                  'product_id' => 24,
                  'province_id' => 5,
                  'median' => 8.00,
                  'min' => 4.60,
                  'max' => 10.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 75,
                  'product_id' => 25,
                  'province_id' => 5,
                  'median' => 9.50,
                  'min' => 4.00,
                  'max' => 16.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 76,
                  'product_id' => 26,
                  'province_id' => 5,
                  'median' => 5.00,
                  'min' => 3.50,
                  'max' => 9.90,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 77,
                  'product_id' => 27,
                  'province_id' => 5,
                  'median' => 5.00,
                  'min' => 3.50,
                  'max' => 11.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 78,
                  'product_id' => 28,
                  'province_id' => 5,
                  'median' => 10.00,
                  'min' => 4.00,
                  'max' => 15.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 79,
                  'product_id' => 29,
                  'province_id' => 5,
                  'median' => 6.00,
                  'min' => 4.15,
                  'max' => 10.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 80,
                  'product_id' => 30,
                  'province_id' => 5,
                  'median' => 8.00,
                  'min' => 5.00,
                  'max' => 12.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 81,
                  'product_id' => 31,
                  'province_id' => 5,
                  'median' => 6.00,
                  'min' => 3.00,
                  'max' => 11.80,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 82,
                  'product_id' => 32,
                  'province_id' => 5,
                  'median' => 10.00,
                  'min' => 4.99,
                  'max' => 20.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 83,
                  'product_id' => 33,
                  'province_id' => 5,
                  'median' => 20.00,
                  'min' => 9.99,
                  'max' => 40.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 84,
                  'product_id' => 34,
                  'province_id' => 5,
                  'median' => 6.00,
                  'min' => 3.00,
                  'max' => 10.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 85,
                  'product_id' => 35,
                  'province_id' => 5,
                  'median' => 10.00,
                  'min' => 3.00,
                  'max' => 20.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 86,
                  'product_id' => 36,
                  'province_id' => 5,
                  'median' => 5.00,
                  'min' => 3.50,
                  'max' => 10.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 87,
                  'product_id' => 37,
                  'province_id' => 5,
                  'median' => 6.00,
                  'min' => 4.00,
                  'max' => 9.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 88,
                  'product_id' => 38,
                  'province_id' => 5,
                  'median' => 10.00,
                  'min' => 3.70,
                  'max' => 15.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 89,
                  'product_id' => 39,
                  'province_id' => 5,
                  'median' => 10.00,
                  'min' => 7.78,
                  'max' => 15.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 90,
                  'product_id' => 40,
                  'province_id' => 5,
                  'median' => 10.00,
                  'min' => 8.00,
                  'max' => 14.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 91,
                  'product_id' => 41,
                  'province_id' => 5,
                  'median' => 5.56,
                  'min' => 3.33,
                  'max' => 13.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 92,
                  'product_id' => 42,
                  'province_id' => 5,
                  'median' => 12.00,
                  'min' => 10.00,
                  'max' => 20.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 93,
                  'product_id' => 43,
                  'province_id' => 5,
                  'median' => 37.50,
                  'min' => 25.00,
                  'max' => 48.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 94,
                  'product_id' => 44,
                  'province_id' => 5,
                  'median' => 19.00,
                  'min' => 8.99,
                  'max' => 30.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 95,
                  'product_id' => 45,
                  'province_id' => 5,
                  'median' => 29.00,
                  'min' => 13.00,
                  'max' => 42.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 96,
                  'product_id' => 46,
                  'province_id' => 5,
                  'median' => 45.00,
                  'min' => 30.00,
                  'max' => 68.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 97,
                  'product_id' => 47,
                  'province_id' => 5,
                  'median' => 36.25,
                  'min' => 22.00,
                  'max' => 59.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 98,
                  'product_id' => 48,
                  'province_id' => 5,
                  'median' => 46.50,
                  'min' => 32.00,
                  'max' => 75.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 99,
                  'product_id' => 49,
                  'province_id' => 5,
                  'median' => 40.00,
                  'min' => 30.00,
                  'max' => 59.99,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
            array(
                  'id' => 100,
                  'product_id' => 50,
                  'province_id' => 5,
                  'median' => 19.00,
                  'min' => 12.00,
                  'max' => 25.00,
                  'reported_at' => new DateTime('2013-10-01'),
                  'created_at' => new DateTime,
                  'updated_at' => new DateTime
            ),
        );

        // Uncomment the below to run the seeder
        DB::table('ibp')->insert($ibp);
    }
}
